### ISSUE TITLE
I couldn't get the GPU name

### ISSUE THREAD

**Issue by seungyongshim** [eBay/nvidiagpubeat#27]
Excuse, me.

My config is here.
```
nvidiagpubeat:
  period: 30s
  query: "name,driver_version,count,index,fan.speed,memory.total,memory.used,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,clocks.gr,clocks.sm,clocks.mem,pstate"
  env: "production"
```

My Result
```json
{
  "index": 3,
  "temperature": {
    "gpu": 33
  },
  "memory": {
    "total": 11172,
    "used": 10
  },
  "utilization": {
    "gpu": 0,
    "memory": 0
  },
  "clocks": {
    "current": {
      "graphics": 0,
      "sm": 0,
      "memory": 0
    }
  },
  "ecs": {
    "version": "1.5.0"
  },
  "power": {
    "limit": 0,
    "draw": 0
  },
  "gpuIndex": 3,
  "gpu_name": 0,
  },
  "count": 4,
  "fan": {
    "speed": 23
  },
  "driver_version": 0,
  "pstate": 8,
  "type": "nvidiagpubeat",
}
```

gpu_name is 0. 
power.limit is 0.
And another field has incorrected value of 0.

https://github.com/eBay/nvidiagpubeat/blob/a013ac43282923c49179b996fce9c6263b4a0acf/nvidia/gpu.go#L90

Please, fix it. My boss is going to happy.

Best regards.
