### ISSUE TITLE
Incompatible with driver version 460.32.03 (because of the two dots)

### ISSUE THREAD

**Issue by alex-milanovic** [eBay/nvidiagpubeat#32]
I believe the current version is not compatible with Nvidia driver version 460.32.03, due to it having two dots in the name.

Please see the end of the line below:

```
2021-01-13T20:22:02.494Z	WARN	elasticsearch/client.go:535	Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xbff7f37a9d203e60, ext:32072702120, loc:(*time.Location)(0x2090e20)}, Meta:common.MapStr(nil), Fields:common.MapStr{"agent":common.MapStr{"ephemeral_id":"fd12b93b-9db1-4e24-9e0d-747229464c00", "hostname":"dca939cfb9c2", "id":"33c198bd-3989-4a66-9683-fe258efbe53b", "type":"nvidiagpubeat", "version":"7.3.3"}, "clocks":common.MapStr{"gr":0, "mem":405, "sm":0}, "count":2, "driver_version":"460.32.03", "ecs":common.MapStr{"version":"1.0.1"}, "fan":common.MapStr{"speed":30}, "gpuIndex":1, "host":common.MapStr{"name":"dca939cfb9c2"}, "index":1, "memory":common.MapStr{"total":24268, "used":5942}, "name":"GeForceRTX3090", "power":common.MapStr{"draw":7.14, "limit":350}, "pstate":8, "temperature":common.MapStr{"gpu":28}, "type":"nvidiagpubeat", "utilization":common.MapStr{"gpu":0, "memory":0}}, Private:interface {}(nil), TimeSeries:false}, Flags:0x0} (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse field [driver_version] of type [float] in document with id 'tvFp_XYBFpUHIuKQj2b6'. Preview of field's value: '460.32.03'","caused_by":{"type":"number_format_exception","reason":"multiple points"}}
```

**Comment by aLeX1443** [comment]
I've tried removing the `driver_version` from the YAML configuration but it still tries to read it for some reason

**Comment by alex-milanovic** [comment]
A temporary workaround seems to be to remove the `driver_version` from the configuration file, i.e., 

```
nvidiagpubeat:
  period: 1s
  query: "--query-gpu=name,count,index,fan.speed,memory.total,memory.used,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,clocks.gr,clocks.sm,clocks.mem,pstate"
  env: "dev"

output.elasticsearch:
  hosts: "${ELASTICSEARCH_HOSTS}"
```

**Comment by deepujain** [comment]
Hello Alex,
Thank you for raising the issue along with workaround. 

Please share the output of below query that has ***driver_version*** on your NVIDIA GPU. 

``` nvidia-smi --query-gpu=name,gpu_bus_id,gpu_serial,gpu_uuid,driver_version,count,index,fan.speed,memory.total,memory.used,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,clocks.gr,clocks.sm,clocks.mem,pstate```

This way, i can re-create the issue with nvidiagpubeat/nvidiasmilocal/localnvidiasmi.go and provide a fix.


Cheers
Deepak

**Comment by deepujain** [comment]
Hello Alex, @aLeX1443 

I am unable to re-create the issue.

nvidigpubeat.yml has driver_version and looks like below 
```
nvidiagpubeat:
  # Defines how often an event is sent to the output
  period: 1s
  # By default the query of type query-gpu is executed to support backward compatibility
  # query: "name,gpu_bus_id,gpu_serial,gpu_uuid,driver_version,count,index,fan.speed,memory.total,memory.used,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,clocks.gr,clocks.sm,clocks.mem,pstate"
  # A generic version of query is supported by nvidiagpubeat for query options like --query-gpu,--query-compute-apps and others.
  # -query-gpu will provide information about GPU.
  query: "--query-gpu=name,gpu_bus_id,gpu_serial,gpu_uuid,driver_version,count,index,fan.speed,memory.total,memory.used,utilization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,clocks.gr,clocks.sm,clocks.mem,pstate"
  # --query-compute-apps will list currently active compute processes.
  # query: "--query-compute-apps=gpu_name,gpu_bus_id,gpu_serial,gpu_uuid,pid,process_name,used_gpu_memory,used_memory"
  env: "test"
  # env can be test or production. test is for test purposes to evaluate funcationality of this beat. Switch to production
```

The output of above query on my real GPU is

```
nvidia-smi --query-gpu=name,gpu_bus_id,gpu_serial,gpu_uuid,driver_version,count,index,fan.speed,memory.total,memory.used,util
ization.gpu,utilization.memory,temperature.gpu,power.draw,power.limit,clocks.gr,clocks.sm,clocks.mem,pstate --format=csv
name, pci.bus_id, serial, uuid, driver_version, count, index, fan.speed [%], memory.total [MiB], memory.used [MiB], utilization.gpu [%], utilization.memory [%], temperature.gpu, power.draw [W], power.li
mit [W], clocks.current.graphics [MHz], clocks.current.sm [MHz], clocks.current.memory [MHz], pstate

Tesla P100-PCIE-16GB, 00000000:08:00.0, 1234567890123, GPU-xxx75xxx-xxxx-xxx-xxxx-1234567890ab, 418.87.00, 1, 0, [Not Supported], 16280 MiB, 0 MiB, 0 %, 0 %, 28, 26.02 W, 250.00 W, 405 MHz, 405 MHz, 71
5 MHz, P0
```
Here the driver_version has two dots `418.87.00`

The resulting output from nvidigpubeat is

```
2021-01-16T21:02:27.389-0800	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2021-01-17T05:02:27.388Z",
  "@metadata": {
    "beat": "nvidiagpubeat",
    "type": "doc",
    "version": "6.5.5"
  },
  "driver_version": "418.87.00",
  "beat": {
    "name": "AA-ABC-11111111",
    "hostname": "AA-ABC-11111111",
    "version": "6.5.5"
  },
  "temperature": {
    "gpu": 28
  },
  "pstate": 0,
  "power": {
    "draw": 26.02,
    "limit": 250
  },
  "gpu_serial": 1234567890123,
  "name": "Tesla100-PCIE-16GB",
  "utilization": {
    "gpu": 0,
    "memory": 0
  },
  "index": 0,
  "fan": {
    "speed": "[NotSupported]"
  },
  "gpu_uuid": "GPU-xxx75xxx-xxxx-xxx-xxxx-1234567890ab",
  "host": {
    "name": "AA-ABC-11111111"
  },
  "gpu_bus_id": "00000000:08:00.0",
  "gpuIndex": 0,
  "memory": {
    "total": 16280,
    "used": 0
  },
  "count": 1,
  "clocks": {
    "sm": 405,
    "mem": 715,
    "gr": 405
  },
  "type": "nvidiagpubeat"
}
```

Each field correctly maps the CSV output from nvidia-smi command.

Cheers
Deepak
